### PR TITLE
Remove hardcoded username

### PR DESCRIPTION
**Pull request by rovanleeuwen**

### CODE REVIEW

**Comment by rovanleeuwen** [comment]
This fixes a hardcoded username in the rsync command for linux

**Comment by alkivi-sas** [comment]
Could you add the parameters remote_user to the class ? and give it a more specific name ? :)
Also, we are not using puppet, are you interested in owing the repo ?

**Comment by rovanleeuwen** [comment]
The remote_user is already part of the class (and used in e.g. osx, it is just not part of the linux rsync).

I am rolling this out as a stop-gap measure for a backup/ I do not think we will be using this long so owning this repo is not an investment I would be willing to make currently.
Since this was such a small change I needed I just make a pull request,

**Comment by alkivi-sas** [comment]
Ok, I see. I missed the host ressource.
Let's pull

**Pull request merged**
